import type { HeroSlide } from "./heroSlide";

/** Copy used when no document exists in `BannerSettings` yet. */
export const DEFAULT_BANNER_COPY = {
  trustBadgeText: "Ahmedabad · Since 2000 · GST Verified",
  headlinePart1: "Rajasthan",
  headlinePart2: "Pipe Traders",
  tagline: "Your Trusted Wholesale Hardware Partner",
  subtextHtml:
    "Established in Ahmedabad, we are a leading wholesale distributor of <strong>premium fittings</strong>, Cable Clips, Ball Valves, Modular Boxes, Nylon Ties, Insulation Tape, Wall Plugs and more.",
  stats: [
    { value: "500+", label: "Products" },
    { value: "12+", label: "Product Lines" },
    { value: "25+", label: "Years Trust" },
    { value: "Pan India", label: "Delivery" },
  ],
  backgroundImageUrl: "/banner-1.png",
} as const;

/** Inline slides used when DB has no carousel or products fail to resolve. */
export const FALLBACK_HERO_SLIDES: HeroSlide[] = [
  {
    tag: "🔥 Hot Selling",
    tagKey: "hot",
    product: {
      id: 1,
      slug: "cable-nail-clips",
      name: "Cable Nail Clips",
      brand: "Hitech Square",
      category: "Cable Clips",
      description: "Cable nail clips for secure wire management on walls and ceilings.",
      image: "/Cable_Clip.png",
      sellerId: "hitech-square",
      sellerName: "Hitech Square",
      firstWithGST: 9.3,
      firstBasic: 7.88,
      firstSize: "4MM",
      qtyPerBag: 750,
      pcsPerPacket: 100,
    },
  },
  {
    tag: "⭐ Most Popular",
    tagKey: "popular",
    product: {
      id: 6,
      slug: "nylon-cable-ties",
      name: "Nylon Cable Ties",
      brand: "Hitech Square",
      category: "Cable Clips",
      description:
        "High-tensile nylon cable ties for bundling, organising, and securing cables and wires.",
      image: "/Cable_Clip.png",
      sellerId: "default",
      sellerName: "Hitech Square",
      firstWithGST: 10.95,
      firstBasic: 9.28,
      firstSize: '100 × 1.8mm (4")',
      qtyPerBag: 600,
      pcsPerPacket: 100,
    },
  },
  {
    tag: "🎁 Combo Products",
    tagKey: "combo",
    product: {
      id: 2,
      slug: "double-nail-clamp",
      name: "Double Nail Clamps",
      brand: "Hitech Square",
      category: "Cable Clips",
      description: "Heavy-duty double nail clamps for extra-strong, vibration-resistant cable fastening.",
      image: "/Nail_Cable_Clip.png",
      sellerId: "default",
      sellerName: "Hitech Square",
      firstWithGST: 93.17,
      firstBasic: 78.96,
      firstSize: "20MM",
      qtyPerBag: 65,
      pcsPerPacket: 50,
    },
  },
  {
    tag: "💎 Sanitary Range",
    tagKey: "premium",
    product: {
      id: 9,
      slug: "ball-valve-white",
      name: "PP Solid White Ball Valve",
      brand: "N-Star",
      category: "Sanitaryware",
      description: "N-Star PP solid white ball valve — short/long handle and plain/threaded.",
      image: "/Cable_Clip.png",
      sellerId: "default",
      sellerName: "N-Star",
      firstWithGST: 32.97,
      firstBasic: 27.94,
      firstSize: '15MM (1/2") Short Handle Plain',
      qtyPerBag: 216,
      pcsPerPacket: 36,
    },
  },
  {
    tag: "🏆 Bestseller",
    tagKey: "best",
    product: {
      id: 4,
      slug: "upvc-pipe-clamp",
      name: "UPVC Pipe Fitting Clamps",
      brand: "Hitech Square",
      category: "Cable Clips",
      description: "Clamps for secure fixing of UPVC pipe fittings to walls and surfaces.",
      image: "/Cable_Clip.png",
      sellerId: "default",
      sellerName: "Hitech Square",
      firstWithGST: 167.44,
      firstBasic: 141.9,
      firstSize: "U-1/2",
      qtyPerBag: 35,
      pcsPerPacket: 100,
    },
  },
];
